#!/bin/bash
set -ex

echo "Running tests..."

export BASE_IMAGE=${1:-"ubuntu/jre:test"}
export BUILD_IMAGE=${2:-"ubuntu/jre:test-builder"}
export M2_CACHE=${3:-"$(pwd)/.m2"}
export MAVEN_IMAGE=${4:-"ubuntu/jre:test-maven"}

compile() {
	javac -source 21 -target 21 $1 $2
}

run_container() {
	docker run --rm -v $PWD:/app:ro -w /app $*
}

export -f compile
export -f run_container

mkdir -p ${M2_CACHE}

CURRENT_DIR="$(dirname $(readlink -f $0))"

for test_dir in "$CURRENT_DIR"/*/
do
    if [[ -x ${test_dir}/runtest ]]; then

        pushd $test_dir

        ./runtest

        popd
    fi
done
