#!/bin/bash
set -ex

echo "Running tests..."

export BASE_IMAGE=${1:-"ubuntu/chiselled-jre:test"}

compile() {
	javac $1 $2
}

run_container() {
	docker run --rm -v $PWD:/app:ro -w /app $3 $1 $2
}

export -f compile
export -f run_container

CURRENT_DIR="$(dirname $(readlink -f $0))"

for test_dir in "$CURRENT_DIR"/*/
do
    pushd $test_dir

    ./runtest

    popd
done
