#!/bin/bash
set -ex

echo "Running tests..."

export BASE_IMAGE=${1:-"ubuntu/chiselled-jre:test"}
export BUILD_IMAGE=${2:-"ubuntu/chiselled-jre:test-builder"}
export M2_CACHE=${3:-"/tmp/.m2"}

compile() {
	javac -source 8 -target 8 $1 $2
}

run_container() {
	docker run --rm -v $PWD:/app:ro -w /app $3 $1 $2
}

export -f compile
export -f run_container

mkdir -p ${M2_CACHE}

CURRENT_DIR="$(dirname $(readlink -f $0))"

for test_dir in "$CURRENT_DIR"/*/
do
    pushd $test_dir

    ./runtest

    popd
done
