ARG UBUNTU_RELEASE=22.04
ARG USER=app
ARG UID=101
ARG GROUP=app
ARG GID=101
ARG CHISEL_VERSION=1.3.0

FROM public.ecr.aws/ubuntu/ubuntu:$UBUNTU_RELEASE@sha256:0525c83b3bd9d8ffe00c8b0401251ef3d7e8fd781390a13537d5806f0a73191e AS builder
ARG USER
ARG UID
ARG GROUP
ARG GID
ARG TARGETARCH
ARG CHISEL_VERSION
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
ADD https://github.com/canonical/chisel/releases/download/v${CHISEL_VERSION}/chisel_v${CHISEL_VERSION}_linux_${TARGETARCH}.tar.gz chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
        ca-certificates-java \
        zstd \
        jq \
        media-types \
        openjdk-8-jre-headless \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /rootfs \
      && chisel cut --root /rootfs \
        openjdk-8-jre-headless_core \
        openjdk-8-jre-headless_locale \
        openjdk-8-jre-headless_security \
        openjdk-8-jre-headless_management \
        openjdk-8-jre-headless_jfr \
        openjdk-8-jre-headless_tools \
        openjdk-8-jre-headless_jplis \
        openjdk-8-jre-headless_jndidns \
        openjdk-8-jre-headless_zipfs \
        openjdk-8-jre-headless_sctp \
        media-types_data \
        base-files_base \
        base-files_bin \
        base-files_chisel \
    && ln -s "$(find /rootfs/usr/lib/jvm/java-8-openjdk-*/jre/bin -name java | sed 's/\/rootfs//')" /rootfs/usr/bin/
RUN install -d -m 0755 -o $UID -g $GID /rootfs/home/$USER \
    && echo -e "root:x:0:\n$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo -e "root:x:0:0:root:/root:/noshell\n$USER:x:$UID:$GID::/home/$USER:/noshell" >/rootfs/etc/passwd
RUN cp /etc/ssl/certs/java/cacerts /rootfs/etc/ssl/certs/java/cacerts

# Create security manifest
COPY print-dpkg-query.awk /
COPY create-manifest.sh /
RUN /bin/bash /create-manifest.sh /rootfs ${TARGETARCH}

FROM scratch
ARG USER
ARG UID
ARG GID
USER $UID:$GID
COPY --from=builder /rootfs /
# Workaround for https://github.com/moby/moby/issues/38710
COPY --from=builder --chown=$UID:$GID /rootfs/home/$USER /home/$USER
ENTRYPOINT ["/usr/bin/java"]
