#!/bin/sh

set -ex

# This tests downloads PDFBox, patches out flaky test, copies javac in the
# container and then builds and runs PDFBox tests
echo "Running Apache PDFBox self-tests"

if [ -z $MAVEN_IMAGE ]; then
    echo 'Please define $MAVEN_IMAGE'
    exit 1
fi

if [ -z $M2_CACHE ]; then
    echo 'Please define $M2_CACHE'
    exit 1
fi

PDFBOX_REPO=https://github.com/vpa1977/pdfbox
VERSION=3.0.0-alpha3
APP=pdfbox
TEST_DIR=`pwd`

docker build -t ${APP} --build-arg MAVEN_IMAGE=${MAVEN_IMAGE} .

DOCKER_OPTS="--rm  \
    --tmpfs /tmp:exec \
    -u app \
    -v ${M2_CACHE}:${M2_CACHE} \
    -v ${TEST_DIR}:${TEST_DIR} \
    -w ${TEST_DIR}/${APP} "

git clone --branch ${VERSION} ${PDFBOX_REPO} || \
    (cd ${APP} && \
     git checkout ${VERSION} &&
     git reset --hard)

# build and tests with chiselled jre
docker run \
    ${DOCKER_OPTS} \
    ${APP} \
        -Dmaven.repo.local="${M2_CACHE}" \
        test
