ARG UBUNTU_RELEASE=22.04
ARG BASE_IMAGE=ubuntu/jre:17_edge
ARG CHISEL_VERSION=0.10.0
ARG TARGETARCH=amd64

FROM public.ecr.aws/ubuntu/ubuntu:$UBUNTU_RELEASE@sha256:1582c29f34a48752e406f1a261fe9545fad895da3f6bb4be55bc82485557564e AS jdk

ARG CHISEL_VERSION
ARG TARGETARCH

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
        ca-certificates-java \
        binutils \
        openjdk-17-jdk \
        maven \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

 RUN jlink --no-header-files --no-man-pages --strip-debug \
    --add-modules ALL-MODULE-PATH --output /opt/java

SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
ADD https://github.com/canonical/chisel/releases/download/v${CHISEL_VERSION}/chisel_v${CHISEL_VERSION}_linux_${TARGETARCH}.tar.gz chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/
RUN mkdir -p /rootfs \
        && chisel cut --root /rootfs coreutils_bins dash_bins

FROM $BASE_IMAGE

COPY --from=jdk /rootfs /
COPY --from=jdk /etc/maven /etc/maven
COPY --from=jdk /usr/share/java /usr/share/java
COPY --from=jdk /usr/share/maven /usr/share/maven

ENV JAVA_HOME=/opt/java

# Add javac compiler for maven (it always recompiles package-info.java)
COPY --from=jdk /opt/java/bin/javac  /opt/java/bin/
# compatibility signatures
COPY --from=jdk /opt/java/lib/ct.sym /opt/java/lib/
# additional jars
COPY --from=jdk /opt/java/lib/*.jar  /opt/java/lib/
# copy modules
COPY --from=jdk /opt/java/lib/modules /opt/java/lib/

ENTRYPOINT [ "/usr/share/maven/bin/mvn" ]
