ARG UBUNTU_RELEASE=22.04
ARG BASE_IMAGE=ubuntu/jre:8_edge
ARG CHISEL_VERSION=1.2.0
ARG TARGETARCH=amd64

FROM public.ecr.aws/ubuntu/ubuntu:$UBUNTU_RELEASE@sha256:c48359e1887a40c4a8396a4c3f40f4b8245bdbb6a64cb5f39b85c80510f0c868 AS jdk

ARG CHISEL_VERSION
ARG TARGETARCH

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
        ca-certificates-java \
        binutils \
        openjdk-8-jdk \
        maven \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
ADD https://github.com/canonical/chisel/releases/download/v${CHISEL_VERSION}/chisel_v${CHISEL_VERSION}_linux_${TARGETARCH}.tar.gz chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/
RUN mkdir -p /rootfs \
        && chisel cut --root /rootfs coreutils_bins dash_bins

FROM $BASE_IMAGE
ARG TARGETARCH

COPY --from=jdk /rootfs /
COPY --from=jdk /etc/maven /etc/maven
COPY --from=jdk /usr/share/java /usr/share/java
COPY --from=jdk /usr/share/maven /usr/share/maven

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-${TARGETARCH}/jre

# Add javac compiler for maven (it always recompiles package-info.java)
COPY --from=jdk /usr/lib/jvm/java-8-openjdk-${TARGETARCH}/bin/javac \
    /usr/lib/jvm/java-8-openjdk-${TARGETARCH}/jre/bin/
COPY --from=jdk /usr/lib/jvm/java-8-openjdk-${TARGETARCH}/lib/tools.jar \
    /usr/lib/jvm/java-8-openjdk-${TARGETARCH}/jre/lib/

ENTRYPOINT [ "/usr/share/maven/bin/mvn" ]
