ARG BUILD_IMAGE=eclipse-temurin:21.0.5_11-jdk-noble
ARG USER=app
ARG UID=101
ARG GROUP=app
ARG GID=101

FROM ${BUILD_IMAGE}

ARG USER
ARG UID
ARG GROUP
ARG GID

RUN install -d -m 0755 -o $UID -g $GID /home/$USER \
    && echo -e "root:x:0:\n$GROUP:x:$GID:" >/etc/group \
    && echo -e "root:x:0:0:root:/root:/noshell\n$USER:x:$UID:$GID::/home/$USER:/noshell" >/etc/passwd

USER $UID:$GID
