#!/bin/bash
set -ex

# This test builds and runs tests for spring-petclinic using Maven inside
# chiselled JRE container

echo "Running Spring Petclinic self-tests"

if [ -z $MAVEN_IMAGE ]; then
    echo 'Please define $MAVEN_IMAGE'
    exit 1
fi

if [ -z $M2_CACHE ]; then
    echo 'Please define $M2_CACHE'
    exit 1
fi

# clone petclinic repository, alternative is to have a submodule here
TEST_DIR=`pwd`
PROJECT=spring-petclinic

PETCLINIC_TAG=spring-boot-3.0.6
PETCLINIC_REPO=https://github.com/vpa1977/${PROJECT}
echo cloning ${PETCLINIC_TAG} ${PETCLINIC_REPO}
git clone --branch ${PETCLINIC_TAG} ${PETCLINIC_REPO} || \
    (cd ${PROJECT} && \
     git checkout ${PETCLINIC_TAG} &&
     git reset --hard)

# We should replace Temurin with our dev container
DOCKER_OPTS="--rm  \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    -v ${M2_CACHE}:${M2_CACHE} \
    -v ${TEST_DIR}:${TEST_DIR} \
    -w ${TEST_DIR}/${PROJECT} "

# now run the tests within our container
docker run \
    ${DOCKER_OPTS} \
    ${MAVEN_IMAGE} \
        -Dmaven.repo.local=${M2_CACHE} \
        -Duser.home=${TEST_DIR} \
        test
