#!/bin/bash
set -ex

# This test builds tests for spring-petclinic with Maven, copies class files
# into the chiselled container and executes them in the container environemnt.
# For OpenJDK 8 we need to use tag on the last commit that used spring-boot 2.X
# as later version requires OpenJDK 17.

echo "Running Spring Petclinic self-tests"

if [ -z $MAVEN_IMAGE ]; then
    echo 'Please define $MAVEN_IMAGE'
    exit 1
fi

if [ -z $M2_CACHE ]; then
    echo 'Please define $M2_CACHE'
    exit 1
fi

# clone petclinic repository, alternative is to have a submodule here
TEST_DIR=`pwd`
PROJECT=spring-petclinic
PROJECT_DIR=${TEST_DIR}/${PROJECT}

PETCLINIC_TAG=spring-boot-2.7.3
PETCLINIC_REPO=https://github.com/vpa1977/${PROJECT}
echo cloning $PETCLINIC_TAG $PETCLINIC_REPO
git clone --branch $PETCLINIC_TAG $PETCLINIC_REPO || \
    (cd ${PROJECT} && \
     git checkout ${PETCLINIC_TAG} &&
     git reset --hard)

DOCKER_OPTS="--rm --tmpfs /tmp:exec \
    -v ${M2_CACHE}:${M2_CACHE} \
    -v ${TEST_DIR}:${TEST_DIR} \
    -w ${TEST_DIR}/spring-petclinic\
    -u app"

# build and tests with chiselled jre
docker run \
    ${DOCKER_OPTS} \
    ${MAVEN_IMAGE} \
        -Dmaven.repo.local="${M2_CACHE}" \
        -Dproject.build.directory=/home/app/build \
        test
