#!/bin/sh

set -ex

# This test builds acmeair application and runs self-tests
echo "Running AcmeAir self-tests"

if [ -z $MAVEN_IMAGE ]; then
    echo 'Please define $MAVEN_IMAGE'
    exit 1
fi

if [ -z $M2_CACHE ]; then
    echo 'Please define $M2_CACHE'
    exit 1
fi

TEST_DIR=`pwd`
PROJECT=acmeair-monolithic-java
TAG=chiselled-demo-17
ACMEAIR_REPO=https://github.com/vpa1977/${PROJECT}

DOCKER_OPTS="--rm  \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    -v ${M2_CACHE}:${M2_CACHE} \
    -v ${TEST_DIR}:${TEST_DIR} \
    -w ${TEST_DIR}/${PROJECT} "

git clone --branch ${TAG} ${ACMEAIR_REPO} || \
    (cd ${PROJECT} && \
     git checkout ${TAG})

# build and tests with chiselled jre
docker run \
    ${DOCKER_OPTS} \
    ${MAVEN_IMAGE} \
        -X -e  -Dmaven.repo.local="${M2_CACHE}" \
        -Duser.home=${TEST_DIR} \
        test
